#!/usr/bin/env python3
"""Phase C — export `ChemicalData` and generate the Rust side.

`rf2aa/chemical.py` is 2 921 lines of mostly *data*: 80 tokens, per-residue atom
names, bond graphs, ideal internal coordinates, LJ parameters, torsion frames.
Retyping it into Rust by hand is both enormous and exactly the kind of work that
introduces silent single-element errors, so it is exported mechanically and then
asserted element-for-element on the Rust side.

Outputs
-------
  rfd2/data/chemical.safetensors   every tensor table (embedded via include_bytes!)
  fixtures/chemical/chemical.json  scalars, string tables, dicts (for tests)
  rfd2/src/chemical_gen.rs         generated Rust: scalars + string tables

The safetensors blob is ~1 MB, so it goes in the binary and there is no
companion data file at runtime (SOP §7).

    PYTHONPATH=<ref> .venv/bin/python python/gen_chemical.py
"""
import json
import os
import sys

os.environ.setdefault("PYTORCH_JIT", "0")

import common
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

RUST_HEADER = '''//! Generated by `python/gen_chemical.py` from the pinned reference's
//! `rf2aa/chemical.py`. **Do not edit by hand** — regenerate instead.
//!
//! Scalars and string tables live here; the numeric tables are in
//! `data/chemical.safetensors`, embedded with `include_bytes!` (SOP §7) and
//! served by `chemical.rs`.
//!
//! Every value is asserted against the reference in `tests/parity_chemical.rs`.

#![allow(dead_code)]

'''


def rust_str_list(name, values, doc=""):
    body = ",\n    ".join(f'"{v}"' for v in values)
    d = f"/// {doc}\n" if doc else ""
    return (f"{d}pub const {name}: [&str; {len(values)}] = [\n    {body},\n];\n\n")


def rust_str_list_of_lists(name, values, doc=""):
    """For aa2long-style tables: tuples of Option<&str> (None -> empty)."""
    width = max(len(v) for v in values)
    rows = []
    for v in values:
        cells = []
        for i in range(width):
            a = v[i] if i < len(v) else None
            cells.append('""' if a is None else f'"{a}"')
        rows.append("    [" + ", ".join(cells) + "]")
    body = ",\n".join(rows)
    d = f"/// {doc}\n" if doc else ""
    return (f"{d}pub const {name}: [[&str; {width}]; {len(values)}] = [\n"
            f"{body},\n];\n\n")


def main():
    # `ChemicalData` does not read its tables from a file — it *computes* the
    # derived ones (`RTs_by_torsion`, `xyzs_in_base_frame`, the reference angles)
    # from ideal internal coordinates at import time. So they depend on the
    # arithmetic in force when the singleton is first built, and exporting them
    # from an unpinned interpreter produces a table that is 1 ULP off in a few
    # entries from the one the pinned reference actually uses.
    #
    # Measured: `RTs_by_torsion[1, 3]` came out `bea9a838` unpinned vs
    # `bea9a839` pinned, and that single ULP moved 37 of 7 668 all-atom
    # coordinates through the chi1..chi4 frame chain.
    import pinned
    pinned.enable()
    common.add_ref_to_path()
    from rf_diffusion.chemical import ChemicalData as ChemData
    cd = ChemData()

    port = common.PORT_ROOT
    data_dir = os.path.join(port, "rfd2", "data")
    os.makedirs(data_dir, exist_ok=True)

    # ---- 1. numeric tables -> safetensors --------------------------------
    tensors = {}
    for k in sorted(vars(cd)):
        v = getattr(cd, k)
        if torch.is_tensor(v):
            t = v.detach().cpu().contiguous()
            if t.dtype == torch.bool:
                t = t.to(torch.int64)
            tensors[k] = t
    from safetensors.torch import save_file
    blob = os.path.join(data_dir, "chemical.safetensors")
    save_file(tensors, blob)
    n_vals = sum(t.numel() for t in tensors.values())
    print(f"  wrote {blob}  ({len(tensors)} tables, {n_vals} values, "
          f"{os.path.getsize(blob)/1e6:.2f} MB)")

    # ---- 2. everything else -> json --------------------------------------
    meta = {"scalars": {}, "lists": {}, "dicts": {}}
    for k in sorted(vars(cd)):
        v = getattr(cd, k)
        if torch.is_tensor(v):
            continue
        if isinstance(v, (int, float, str, bool)):
            meta["scalars"][k] = v
        elif isinstance(v, dict):
            meta["dicts"][k] = {str(a): b for a, b in v.items()}
        elif isinstance(v, (list, tuple)):
            meta["lists"][k] = json.loads(json.dumps(v, default=str))
    common.write_json("chemical", "chemical", meta)

    # ---- 3. generated Rust ------------------------------------------------
    out = [RUST_HEADER]

    out.append("// ---- scalars ----\n")
    for k in sorted(meta["scalars"]):
        v = meta["scalars"][k]
        if isinstance(v, bool):
            out.append(f"pub const {k.upper()}: bool = {str(v).lower()};\n")
        elif isinstance(v, int):
            out.append(f"pub const {k.upper()}: usize = {v};\n")
        elif isinstance(v, float):
            out.append(f"pub const {k.upper()}: f32 = {v}f32;\n")
        else:
            out.append(f'pub const {k.upper()}: &str = "{v}";\n')
    out.append("\n")

    out.append(rust_str_list("NUM2AA", cd.num2aa,
                             "token index -> residue/atom name (NAATOKENS)"))
    out.append(rust_str_list("ONE_LETTER", cd.one_letter,
                             "one-letter codes for the 22 protein tokens"))
    out.append(rust_str_list("FRAME_PRIORITY2ATOM", cd.frame_priority2atom,
                             "element ordering used by atom_type_index"))
    out.append(rust_str_list("AA2TIP", [x if x else "" for x in cd.aa2tip],
                             "tip atom per residue"))
    out.append(rust_str_list("METAL_RES_NAMES", cd.METAL_RES_NAMES, ""))
    out.append(rust_str_list_of_lists("AA2LONG", cd.aa2long,
                                      "per-residue atom names, heavy+H order"))
    out.append(rust_str_list_of_lists("AA2LONGALT", cd.aa2longalt,
                                      "symmetry-swapped atom naming"))
    out.append(rust_str_list_of_lists("AA2ELT", cd.aa2elt,
                                      "per-residue element symbols"))

    # atom_num is a plain int list
    body = ", ".join(str(x) for x in cd.atom_num)
    out.append(f"/// atomic numbers matching FRAME_PRIORITY2ATOM\n"
               f"pub const ATOM_NUM: [i64; {len(cd.atom_num)}] = [{body}];\n\n")

    rust_path = os.path.join(port, "rfd2", "src", "chemical_gen.rs")
    with open(rust_path, "w") as fh:
        fh.write("".join(out))
    print(f"  wrote {rust_path}  ({len(''.join(out))} bytes)")

    # ---- 4. a summary the test can assert on ------------------------------
    print(f"\nNAATOKENS={cd.NAATOKENS} NHEAVY={cd.NHEAVY} NTOTAL={cd.NTOTAL} "
          f"NNAPROTAAS={cd.NNAPROTAAS} UNKINDEX={cd.UNKINDEX} "
          f"NBTYPES={cd.NBTYPES}")


if __name__ == "__main__":
    main()
